contributing.md
configcat/swift-sdk pull request #13
Opened 2021-04-13 21:28 UTC by kp-cat

### Describe the purpose of your pull request

CONTRIBUTING.md is added.

2021-04-29 12:17 UTC, z4kn4fein approved these changes

2021-05-06 12:00 UTC, laliconfigcat requested changes

2021-05-06 12:00 UTC, laliconfigcat commented on CONTRIBUTING.md
> +2. Open menu Product
```suggestion
2. Open Product menu
```

2021-05-06 12:00 UTC, laliconfigcat commented on CONTRIBUTING.md
> +2. Open menu Product
```suggestion
2. Open Product menu
```

2021-05-09 22:17 UTC, merged