Road to configV6
configcat/swift-sdk pull request #41
Opened 2024-02-29 22:02 UTC by z4kn4fein

Implements config v6 support.

Features/improvements:
* [x] Fetch new config json version (`config_v6.json`) and update config model
* [ ] SDK key format validation (when client is not set up to use local-only flag overrides)
* [x] AND conditions
* [x] New condition types
   * Prerequisite flag condition
   * Segment condition
* [x] Changed comparison operators
   * (NOT) CONTAINS ANY OF
* [x] New comparison operators
   * BEFORE/AFTER
   * TEXT (NOT) EQUALS (both hashed and cleartext)
   * TEXT (NOT) STARTS/ENDS WITH ANY OF (both hashed and cleartext)
   * ARRAY CONTAINS ANY OF (both hashed and cleartext)
* [x] Percentage options within targeting rules
* [x] Percentage options based on custom attributes
* [x] Custom User Object attribute handling (don't force string values + autoconversions under the hood)
* [x] User Object attribute/comparison value trimming
* [x] Comparison value hashing changes (SHA256, salting)
* [ ] ~Flag overrides vs. config json salt and segments~
* [x] `EvaluationDetails.getMatchedTargetingRule`/`getMatchedPercentageOption` properties (rename + set combinations correctly)
* [x] Update `ConfigCatClient.getKeyAndValue`

Tests: 
* [x] Update cache key/payload tests
* [x] Evaluation matrix tests
  * Config v1 features (both V1 & V2)
  * Config v2 features
* [x] Evaluation log tests
* [ ] SDK key format validation
* [x] Custom User Object attribute handling (don't force string values + autoconversions under the hood)
* [x] Flag overrides vs. prerequisite flags (circular dependency, comparison value type mismatch, dependent/prereq flag overriding)
* [ ] ~Flag overrides vs. config json salt and segments~
* [x] `EvaluationDetails.getMatchedTargetingRule`/`getMatchedPercentageOption` properties (rename + set combinations correctly)
* [x] Special character tests (https://trello.com/c/qh4jHrvm)
* [x] User attribute / comparison value trim tests (https://trello.com/c/vt8FFrSZ)
* [x] Comparison attribute and comparison value trimming tests (https://trello.com/c/vt8FFrSZ)
* [x] Comparison attribute conversion to canonical string representation tests (https://trello.com/c/CZgGrrcb)

Related improvements/fixes:
* [ ] Dynamically typed languages should log a warning when default value doesn't match the setting type (see https://trello.com/c/Le6vimGu)
* [x] We should go to the cache in all polling modes instead of using the in memory variable (see https://trello.com/c/rreKm64A)
* [x] Improve message of log event 1103 (https://trello.com/c/Mb7rvm64)

### Requirement checklist (only if applicable)

- [x] I have covered the applied changes with automated tests.
- [x] I have executed the full automated test set against my changes.
- [x] I have validated my changes against all supported platform versions.
- [x] I have read and accepted the [contribution agreement](https://github.com/configcat/legal/blob/main/contribution-agreement.md).

2024-03-18 20:24 UTC, adams85 requested changes
Besides the comments,
* Although the checkbox for [this test](https://github.com/configcat/.net-sdk/blob/4692622a4cb54fce272b3689f6d13dee3be8e96b/src/ConfigCat.Client.Tests/BasicConfigCatClientIntegrationTests.cs#L464-L477) is checked, I couldn't find it.
* The error message of `FlagEvaluator.validateFlagType` is not consistent with other SDKs. See https://github.com/configcat/.net-sdk/blob/4692622a4cb54fce272b3689f6d13dee3be8e96b/src/ConfigCatClient/Extensions/TypeExtensions.cs#L11

2024-03-20 17:20 UTC, adams85 requested changes
Another (hopefully last) batch of minor change requests.

Besides these, please
* [ ] Add the warning about allowed generic arguments ("The generic parameter `Value` represents...") to `ConfigCatClient.getValue` and `getValueDetails` as well.

2024-03-20 17:20 UTC, adams85 commented on Sources/ConfigCat/Config.swift
> +    @objc public let percentageOptions: [PercentageOption]
```suggestion
    /// The list of percentage options associated with the targeting rule or empty if the targeting rule has a served value THEN part.
    @objc public let percentageOptions: [PercentageOption]
```

2024-03-20 17:20 UTC, adams85 commented on Sources/ConfigCat/Config.swift
> +    @objc public let stringArrayValue: [String]?
```suggestion
    /// The value that the User Object attribute is compared to, when the comparator works with a single text comparison value.
    @objc public let stringValue: String?
    
    /// The value that the User Object attribute is compared to, when the comparator works with a numeric comparison value.
    public let doubleValue: Double?
    
    /// The value in Objective-C format that the User Object attribute is compared to, when the comparator works with a numeric comparison value.
    @objc public let doubleValueObjC: NSNumber?
    
    /// The value that the User Object attribute is compared to, when the comparator works with an array of text comparison values.
    @objc public let stringArrayValue: [String]?
```

2024-03-20 17:20 UTC, adams85 commented on Sources/ConfigCat/Config.swift
> +    @objc public let variationId: String?
```suggestion
    /// The value associated with the targeting rule.
    @objc public let value: SettingValue
    
    /// Variation ID (for analytical purposes).
    @objc public let variationId: String?
```

2024-03-20 17:20 UTC, adams85 commented on Sources/ConfigCat/Config.swift
>      /// The rule's variation ID (for analytical purposes).
```suggestion
    /// A number between 0 and 100 that represents a randomly allocated fraction of the users.
    @objc public let percentage: Int

    /// Variation ID (for analytical purposes).
```

2024-03-20 17:20 UTC, adams85 commented on Sources/ConfigCat/Config.swift
> +    /// Checks whether the comparison attribute is equal to any of the comparison values.
❤️

2024-03-20 17:20 UTC, adams85 commented on Sources/ConfigCat/ConfigCatUser.swift
> +     * all other values are automatically converted to `string` (a warning will be logged but evaluation will continue as normal).
```suggestion
     * all other values are automatically converted to `String` (a warning will be logged but evaluation will continue as normal).
```

2024-03-20 17:20 UTC, adams85 commented on Sources/ConfigCat/ConfigCatUser.swift
> +     * accept `String` values containing a properly formatted, valid `Int`, `UInt`, `Double`, or `Float` value,
```suggestion
     * accept `String` values containing a properly formatted, valid `Double` value,
```

2024-03-20 17:20 UTC, adams85 commented on Sources/ConfigCat/ConfigCatUser.swift
> +     * accept `String` values containing a properly formatted, valid `Int`, `UInt`, `Double`, or `Float` value,
```suggestion
     * accept `String` values containing a properly formatted, valid `Double` value,
```

2024-03-20 18:40 UTC, z4kn4fein commented on Sources/ConfigCat/RolloutEvaluator.swift
> +            }
Done

2024-03-20 18:40 UTC, z4kn4fein commented on Sources/ConfigCat/RolloutEvaluator.swift
> +                guard let length = Int(parts[0].trimmingCharacters(in: .whitespaces)), length > 0 else {
Done

2024-03-20 18:40 UTC, z4kn4fein commented on Sources/ConfigCat/EvaluationLogger.swift
> +        }
Done

2024-03-20 18:40 UTC, z4kn4fein commented on Sources/ConfigCat/Config.swift
> +    /// The dictionary of settings.
Done

2024-03-20 18:40 UTC, z4kn4fein commented on Sources/ConfigCat/Config.swift
> +    /// The setting's default value used when no targeting rules are matching during an evaluation process.
Done

2024-03-20 18:41 UTC, z4kn4fein commented on Sources/ConfigCat/Config.swift
> +    /// The setting's type. It can be Bool, String, Int, Float.
Done

2024-03-20 18:41 UTC, z4kn4fein commented on Sources/ConfigCat/Config.swift
> +    @objc public let percentageOptions: [PercentageOption]
Done

2024-03-20 18:41 UTC, z4kn4fein commented on Sources/ConfigCat/Config.swift
> +    @objc public let stringArrayValue: [String]?
Done

2024-03-20 18:41 UTC, z4kn4fein commented on Sources/ConfigCat/Config.swift
>      /// The rule's variation ID (for analytical purposes).
Done

2024-03-20 18:41 UTC, z4kn4fein commented on Sources/ConfigCat/Config.swift
> +    /// Checks whether the comparison attribute is equal to any of the comparison values.
Don.... oops, almost!

2024-03-20 18:41 UTC, z4kn4fein commented on Sources/ConfigCat/ConfigCatUser.swift
> +     * all other values are automatically converted to `string` (a warning will be logged but evaluation will continue as normal).
Done

2024-03-20 18:42 UTC, z4kn4fein commented on Sources/ConfigCat/ConfigCatUser.swift
> +     * accept `String` values containing a properly formatted, valid `Int`, `UInt`, `Double`, or `Float` value,
Done

2024-03-20 18:42 UTC, z4kn4fein commented on Sources/ConfigCat/ConfigCatUser.swift
> +     * accept `String` values containing a properly formatted, valid `Int`, `UInt`, `Double`, or `Float` value,
Done

2024-03-20 18:45 UTC, z4kn4fein commented
> Another (hopefully last) batch of minor change requests.
> 
> Besides these, please
> 
> * [ ]  Add the warning about allowed generic arguments ("The generic parameter `Value` represents...") to `ConfigCatClient.getValue` and `getValueDetails` as well.

It's there on the client's functions: https://github.com/configcat/swift-sdk/blob/c748d1bab8fc64f6b11cba9f131e5fbd789ed3b9/Sources/ConfigCat/ConfigCatClient.swift#L165-L197
Did you mean somewhere else?

2024-03-21 07:42 UTC, adams85 commented
> Did you mean somewhere else?

Yep, I meant `ConfigCatClientSnapshot.getValue`, just couldn't type it out... :)

2024-03-21 09:29 UTC, adams85 approved these changes

2024-03-21 10:00 UTC, merged